Feature/#6 create crud for stop words
sb-github/platform-laravel pull request #17
Opened 2018-01-24 14:18 UTC by ComradeYanis

Merge "feature/#6 create crud for stop words" with "develop"

2018-01-24 14:39 UTC, HarisUa requested changes

2018-01-24 14:39 UTC, HarisUa commented on app/Http/Controllers/StopWordController.php
> +            'title' => 'required|max:60',
title must be unique

2018-01-24 14:39 UTC, HarisUa commented on app/Http/Controllers/StopWordController.php
> +                $stop_word = StopWord::create($new);
For what we need create this (`$new`) array? use $value

2018-01-24 14:39 UTC, HarisUa commented on app/StopWord.php
> +    protected $hidden = array('pivot');
This model has no relationships and dont have `pivot` column.

2018-01-24 16:02 UTC, 4rtHurB commented
Can we store by this API array of stop words (not one stop word)?

2018-01-27 17:05 UTC, HarisUa approved these changes

2018-01-27 17:05 UTC, merged